### ISSUE TITLE
Remove extraneous `.stversions` folder from the repository

### ISSUE THREAD

**Issue by Calinou** [MissLav/LibreQuake#16]
https://github.com/MissLav/LibreQuake/commit/e3ef662f73e5d3d2f32a54a831eb352fa5c47ea5 has added a `.stversions/` folder to the repository, which contains previous versions of various files (it's used by Syncthing). Since Git offers version history, this folder is not most likely not necessary and could be removed.

It might be worth adding `.stversions/` to `~/.config/git/ignore` to avoid committing it in the future. (This is a global `.gitignore` file which will affect every repository on the system.)

**Comment by MissLav** [comment]
ill fix it danke for pointing it out

**Comment by MissLav** [comment]
issue is not fixed by ```Lottie in Rat World
#9973```

**Comment by MissLav** [comment]
changed not to now
